#!/bin/sh

# Profile file, runs on login. Environmental variables are set here.

# Add $HOME/.local/bin to $PATH
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"

# Default programs
export EDITOR="nvim"
export PAGER="less"

# Setup folder
[ ! -d  "${XDG_CONFIG_HOME:-$HOME/.config}/wget" ] && mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/wget"
[ ! -f  "${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc" ] && touch "${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
[ ! -d  "${XDG_CONFIG_HOME:-$HOME/.config}/git" ] && mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/git"
[ ! -f  "${XDG_CONFIG_HOME:-$HOME/.config}/git/gitconfig" ] && touch "${XDG_CONFIG_HOME:-$HOME/.config}/git/gitconfig"

# Clean up $HOME
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export GIT_CONFIG_GLOBAL="${XDG_CONFIG_HOME:-$HOME/.config}/git/gitconfig"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export HISTFILE="$XDG_DATA_HOME/history"

# Pash password manager
export PASH_KEYID=71EC3722D2EFFE62F924C6CF2CF60B4D63C9A536
export PASH_PATTERN="A-Z-a-z-0-9$%^&*?(){}[]-_+=:;/|<>"
export PASH_LENGTH=32
export PASH_TIMEOUT=30

# Fucking Fast File
export FFF_FAV1=/tmp

# Other programs settings
export MOZ_USE_XINPUT2="1"
export GCC_COLORS="error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01"
export FZF_DEFAULT_OPTS="\
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#b4befe,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
--color=selected-bg:#45475a \
--extended --cycle \
--info=inline --border=rounded --layout=reverse --height=70%"

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
