# General options
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'
set -g focus-events on
set -g status-position top
set -s escape-time 0
set -g status-interval 5
setw -g mode-keys vi
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -ogq @catppuccin_pane_status_enabled "yes" # set to "yes" to enable
set -ogq @catppuccin_pane_border_status "yes" # set to "yes" to enable

# Load plugins
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'
run '~/.config/tmux/plugins/tpm/tpm'
