# Status
set -g status-interval 1
set -g escape-time 0
set -g repeat-time 500
set -g display-time 1500
set -g status-position top

# Terminal colors
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

# Enable focus events
set -g focus-events on

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on
setw -g mode-keys vi

# Make index start from 1
set -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window
