#!/bin/sh

# xinitrc runs automatically when you run startx.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Activate DBus environment variables
dbus-update-activation-environment --all

# Start dwm with dbus-launch
exec dbus-launch --exit-with-session /usr/local/bin/dwm
