#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# Add programs which you want to run after logging in

# Use xrandr to set screen resolution
xrandr --output "Virtual-1" --mode "1366x768"

# Set wallpaper
xwallpaper --zoom $HOME/.local/share/wallpapers/wallpaper.png

# Hide mouse cursor after 3 sec.
unclutter --root --timeout 3 &

# Start dwm bar
sh $HOME/.local/bin/dwm_barrr &
