#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# Add programs which you want to run in the backgroup

# Use xrandr to set screen resolution
xrandr --output "LVDS-1" --mode "1366x768" &

# Add compositing
xcompmgr &

# Hide mouse
unclutter-xfixes --timeout 3 &

# Set wallpaper
xwallpaper --zoom $HOME/.local/share/wallpapers/wallpaper.png &

# Start dwm bar
sh $HOME/.local/bin/dwm_bar &
