#!/bin/sh

# Handle custom keys for nsxiv
# The handler is invoked by pressing Ctrl-x.
# The next key combo is passed as its first argument.
# There is also an example script installed together 
# with nsxiv as /usr/share/doc/nsxiv/examples/key-handler.

while read -r file
do
	case "$1" in
		"y") xclip -selection clipboard -target image/png "$file" ;;
		"w") set_wallpaper "$file" ;;
	esac
done
