#!/bin/sh

# Handle custom keys for nsxiv
# The handler is invoked by pressing ctrl-x

while read -r file
do
    case "$1" in
        "y") xclip -selection clipboard -target image/png "$file" ;;
        "w") wallpaper "$file" ;;
        "d") rm -f -- "$file" ;;
    esac
done
