import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
]

[shell]
program = "/usr/bin/bash"
args = ["-l"]

[window]
decorations = "None"
decorations_theme_variant = "Dark"

[scrolling]
history = 3000
multiplier = 8

[font]
normal.family = "Hack Nerd Font Mono"
size = 14

[mouse]
hide_when_typing = true
